# Generated by Django 4.2.2 on 2023-06-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descripcion', models.CharField(blank=True, max_length=50, verbose_name='Descripcion')),
                ('precio', models.IntegerField(blank=True, verbose_name='Precio')),
                ('stock', models.IntegerField(blank=True, verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
            ],
        ),
    ]
