# Generated by Django 4.2.2 on 2023-07-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetParadise', '0002_boleta_alter_tienda_descripcion_alter_tienda_precio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detalle_boelta',
            new_name='detalle_boleta',
        ),
    ]
