# Generated by Django 4.2.2 on 2023-07-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetParadise', '0003_rename_detalle_boelta_detalle_boleta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_boleta',
            old_name='cantidad',
            new_name='cantidad',
        ),
        migrations.AddField(
            model_name='boleta',
            name='impuesto_envio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Impuesto de envio'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='impuesto_pago',
            field=models.IntegerField(blank=True, null=True, verbose_name='Impuesto de pago'),
        ),
    ]
