# Generated by Django 4.2.2 on 2023-07-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetParadise', '0004_rename_stock_detalle_boleta_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='impuesto_envio',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='impuesto_pago',
        ),
    ]
