# Generated by Django 4.2.2 on 2023-07-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetParadise', '0005_remove_boleta_impuesto_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('PP', 'Procesando Pedido'), ('EN', 'Enviado'), ('ENP', 'Entregado al Cliente')], default='Procesando Pedido', max_length=20),
            preserve_default=False,
        ),
    ]
