# Generated by Django 4.2.2 on 2023-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetParadise', '0006_boleta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('PP', 'Procesando Pedido'), ('ENP', 'En Proceso'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='Procesando Pedido', max_length=20),
        ),
    ]
