# Generated by Django 4.2.2 on 2023-07-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetParadise', '0007_alter_boleta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('PP', 'Procesando Pedido'), ('ENP', 'En Proceso'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PP', max_length=3),
        ),
    ]
